// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function none() {
  return /* () */0;
}

function make(a, cb) {
  return Curry._1(cb, a);
}

function map(f, a, cb) {
  return Curry._1(a, (function (param) {
                return Curry._1(cb, Curry._1(f, param));
              }));
}

function flatten(a, cb) {
  return Curry._1(a, (function (b) {
                return Curry._1(b, cb);
              }));
}

function flatMap(f, a) {
  return (function (param) {
      return map(f, a, (function (b) {
                    return Curry._1(b, param);
                  }));
    });
}

exports.none    = none;
exports.make    = make;
exports.map     = map;
exports.flatten = flatten;
exports.flatMap = flatMap;
/* No side effect */
